alias pro='cd /Users/anonymous/Desktop/projects'
alias meet='cd /Users/anonymous/Desktop/projects/meetsmore'
alias mei='cd /Users/anonymous/Desktop/projects/meish'
alias res='cd /Users/anonymous/Desktop/research_project'
alias cod='cd /Users/anonymous/Desktop/coding_memo'
